AWSTemplateFormatVersion: 2010-09-09
Description: EC2 template for cicd exercise4
Parameters:
Resources:
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH access
      VpcId: vpc-0470f5490650f1db8
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-052efd3df9dad4825
      KeyName: "VocareumKey2"
      SecurityGroupIds:
        - !Ref SG
      Tags:
        - Key: project
          Value: udacity