version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/

commands:
  print-pipeline-id :
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  test-job:
    <<: *defaults
    steps:
      - print-pipeline-id

workflows:
  say-hello-workflow:
    jobs:
      - test-job
