version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/

jobs:
  test-job:
    <<: *defaults
    steps:
      - run: exit 1
      - run:
          name: job execution returned 1
          command: echo "Test failure handling was a success"
          when: on_fail

workflows:
  sample-workflow:
    jobs:
      - failure-handling
