version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/

commands:
  failure-handling:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: return 1
      - run:
        name: job execution returned 1
        command: echo "Test failure handling was a success"
        when: on_fail 

jobs:
  test-job:
    <<: *defaults
    steps:
      - print-pipeline-id

workflows:
  sample-workflow:
    jobs:
      - failure-handling
