version: 2.1
defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create cloudformation stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name cicd-stack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  configure-infrastructure:
    docker:
      - image: python:3.11-rc-alpine
      # - image: cimg/python:3.7
    steps:
      - checkout
      - run: python --version
      - add_ssh_keys:
          fingerprints:
            - "51:14:d5:4e:fa:d5:d3:1b:7b:5b:aa:fb:a9:0d:ee:ca"
      - run:
          name: install ansible
          command: |
            apk add --update ansible
      - run:
          name: configure server
          command: |
            ansible-playbook -i inventory main.yml
  smoke-test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi
workflows:
  workflow1:
    jobs:
      # - create-infrastructure
      # - configure-infrastructure
      - smoke-test
