version: 2.1
defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/
jobs:
  job1:
    <<: *defaults
    steps:
      - run: checkout
      - run: echo "hello world"
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create cloudformation stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name cicd-stack-${CIRCLE_WORKFLOW_ID} \
              --region us-east-1
workflows:
  workflow1:
    jobs:
      - create-infrastructure
